### ISSUE TITLE
Version 2.3.0 relies on jinja2 by default

### ISSUE THREAD

**Issue by fedarko** [altair-viz/altair#1262]
Hi, and thanks for your work on Altair! I've been working with Altair by using it to generate a Vega-Lite JSON file (which is later loaded in a browser using Vega-Embed). Since this process doesn't involve using any rendering platforms from the python side of things, I've just been installing Altair from conda alone (without also installing `jupyterlab` or `notebook`, as detailed on [Altair's installation page](https://altair-viz.github.io/getting_started/installation.html)).

This approach was working for me, but version 2.3.0 of altair doesn't seem to work when used in this way (it requires the jinja2 library, which it does not automatically install via conda). Here are minimal steps to reproduce this error, using an install into a new conda environment called `at`:

<pre>
$ conda create -n at -c conda-forge altair
[...]
$ source activate at
$ python
>>> import altair
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v2 import *
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/vegalite/v2/__init__.py", line 2, in <module>
    from .schema import *
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/vegalite/v2/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/vegalite/v2/schema/core.py", line 6, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/utils/__init__.py", line 12, in <module>
    from .html import spec_to_html
  File "/home/marcus/Software/miniconda2/envs/at/lib/python3.6/site-packages/altair/utils/html.py", line 3, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
</pre>

Replacing `altair` in the conda environment creation with `altair=2.2.2` fixes this problem:

<pre>
$ conda deactivate
$ conda create -n at2 -c conda-forge <strong>altair=2.2.2</strong>
[...]
$ source activate at2
$ python
>>> import altair
>>>
</pre>

Installing `jinja2` into an `altair=2.3.0` environment seems to fix the problem as well.

I know that installing `notebook` and `jupyterlab` via conda also installs `jinja2` (not sure about Colab), so this error seems to be specific to the situation of using Altair in a standalone fashion. I can switch to using something like pdvega for standalone Vega-Lite JSON generation if needed, but I figured I should let you know about this issue (not sure if the lack of support is intentional or not). Thank you!

**Comment by jakevdp** [comment]
Hi – that looks like an issue with dependencies in the conda-forge recipe. I'll open an issue there.

**Comment by jakevdp** [comment]
This should be fixed by https://github.com/conda-forge/altair-feedstock/pull/22

**Comment by mkaut** [comment]
I just installed schemapi using `pip install schemapi` on python 3.8 (straight python, no conda) and it complains about missing jinja2 on `import schemapi` - so it looks the dependency is missing in pip as well..
