### ISSUE TITLE
Unable to pickle or copy charts

### ISSUE THREAD

**Issue by bergtholdt** [altair-viz/altair#1681]
I'm unable to pickle a chart. Consider this minimal example:

```python
import pickle
import altair
from vega_datasets import data
iris = data.iris()
ch = altair.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)

with open('chart.pck', 'wb') as fid:
    pickle.dump(ch, fid)

with open('chart.pck', 'rb') as fid:
    pch = pickle.load(fid)
```

Running this results in a RecursionError:
```
(py36) C:\Develop\plab>python sandbox\test_altair_pickle.py                                              
Traceback (most recent call last):                                                                       
  File "sandbox\test_altair_pickle.py", line 15, in <module>                                             
    pch = pickle.load(fid)                                                                               
  File "C:\opt\Anaconda3\envs\py36\lib\site-packages\altair\utils\schemapi.py", line 213, in __getattr__ 
    if attr in self._kwds:                                                                               
  File "C:\opt\Anaconda3\envs\py36\lib\site-packages\altair\utils\schemapi.py", line 213, in __getattr__ 
    if attr in self._kwds:                                                                               
  File "C:\opt\Anaconda3\envs\py36\lib\site-packages\altair\utils\schemapi.py", line 213, in __getattr__ 
    if attr in self._kwds:                                                                               
  [Previous line repeated 330 more times]                                                                
RecursionError: maximum recursion depth exceeded while calling a Python object                           ```
```

It can be fixed using

```python
    def __getattr__(self, attr):
        # reminder: getattr is called after the normal lookups
        if attr == '_kwds': 
            raise AttributeError()
        if attr in self._kwds:
            return self._kwds[attr]
        else:
            try:
                _getattr = super(SchemaBase, self).__getattr__
            except AttributeError:
                _getattr = super(SchemaBase, self).__getattribute__
            return _getattr(attr)
```

I can submit a pull request if desired.

**Comment by jakevdp** [comment]
I would avoid pickle and instead use ``to_json``/``from_json``. Pickle is quite brittle.

**Comment by bergtholdt** [comment]
But the `to_json` / `from_json` will change my chart as you commented in another issue #1644. I would really like to save/load a chart from file and have an equivalent object.

The change in __getattr__ is minimal in my opinion, I just added the two lines:
```
  if attr == '_kwds': 
            raise AttributeError()
```
which should be there anyways IMO. If you don't like the pickle argument, then maybe you buy the copy argument:

```python
import pickle
import altair
from vega_datasets import data
import copy

iris = data.iris()
ch = altair.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)

cch = copy.copy(ch)
```
BAM, infinite recursion.

**Comment by jakevdp** [comment]
OK, feel free to submit a fix – the ground truth for this code is in tools/schemapi.

**Comment by jakevdp** [comment]
(FYI, ``ch.copy()`` will do the right thing, and is the preferred method of copying a chart even after this bug is fixed)
