### ISSUE TITLE
ImportError: cannot import name ConverterMapping when running in docker with python27

### ISSUE THREAD

**Issue by monchier** [altair-viz/altair#1733]
Run a docker container out of `ubuntu:19.04`
```
docker run -it ubuntu:19.04 bash
```
Inside the container:
```
apt-get update && apt-get install python python-pip build-essential
pip install altair
```
Then,
```
echo """
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)""" > test.py
python test.py
```

## Expected behavior
No exception is raised

## Actual behavior
This exception is raised:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import altair as alt
  File "/usr/local/lib/python2.7/dist-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/usr/local/lib/python2.7/dist-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v3 import *
  File "/usr/local/lib/python2.7/dist-packages/altair/vegalite/v3/__init__.py", line 2, in <module>
    from .schema import *
  File "/usr/local/lib/python2.7/dist-packages/altair/vegalite/v3/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/altair/vegalite/v3/schema/core.py", line 6, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined
  File "/usr/local/lib/python2.7/dist-packages/altair/utils/__init__.py", line 14, in <module>
    from .plugin_registry import PluginRegistry
  File "/usr/local/lib/python2.7/dist-packages/altair/utils/plugin_registry.py", line 3, in <module>
    import entrypoints
  File "/usr/lib/python2.7/dist-packages/entrypoints.py", line 16, in <module>
    import configparser
  File "/usr/local/lib/python2.7/dist-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping
```

Note: this happens for Python2.7 and with the above docker setup.

**Comment by jakevdp** [comment]
Looks like an issue with the [entrypoints package](https://github.com/takluyver/entrypoints); likely a problem with Python 2 compatibility. I'd suggest raising the issue there.

Also, I'd suggest migrating to Python 3: these sorts of issues with Py2 will crop up more and more frequently, especially with Py2 EOL a couple months away.

**Comment by monchier** [comment]
The problem seems to be `apt-get` installing `configparser` and `pip` not being able to remove it. Added a comment to https://github.com/streamlit/streamlit/issues/345#issuecomment-543368950 that could be relevant if interested.

**Comment by jakevdp** [comment]
Thanks. Aside from not installing packages whose existence is problematic for the ``entrypoints`` module, I'm not sure what we can do about this from Altair. I maintain that this is an issue with ``entrypoints``, and any fix will be in that package.
