### ISSUE TITLE
Crash on saving figure

### ISSUE THREAD

**Issue by biotemon** [altair-viz/altair#1771]
Hello, 

I am trying to save a figure, but the following line is crashing. I don't find any clue or way to fix it. Any idea is really appreciated.

`nodiffex_plot.save("fig4_diffex_waf_volc_micro_nodiffex_nov_4.svg")`

Traceback (most recent call last):
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1055, in _send_output
    self.send(chunk)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 977, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 480, in save
    result = save(**kwds)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/altair/utils/save.py", line 104, in save
    scale_factor=scale_factor, **kwargs)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/altair/utils/mimebundle.py", line 56, in spec_to_mimebundle
    vegalite_version=vegalite_version, **kwargs)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/altair/utils/headless.py", line 168, in compile_spec
    spec, mode, scale_factor)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 659, in execute_async_script
    'args': converted_args})['value']
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 1055, in _send_output
    self.send(chunk)
  File "/Users/tito-admin/miniconda3/lib/python3.7/http/client.py", line 977, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

**Comment by jakevdp** [comment]
That traceback means nothing to me either... to be honest, I'm thinking about removing the selenium codepaths from the package because it brings up too many mysterious errors like this.

Are you able to save a small sample chart (I'm thinking maybe your dataset is very large and this is causing issues?)

**Comment by biotemon** [comment]
Small figures are working fine. I am pretty sure the dataframe feeding the figure is very big. I also tried the png option as well as the webdriver='firefox' options and the crash repeats.

**Comment by jakevdp** [comment]
If it works for smaller datasets, I suspect you're hitting some data transfer limit within Selenium.
