### ISSUE TITLE
Schema validation error fails to print

### ISSUE THREAD

**Issue by paulmelis** [altair-viz/altair#1935]
```
$ cat test.py
import pandas, altair

d = [{'WijkenEnBuurten': 'Nederland', 'Codering_3': 'NL00', 'Mannen_6': 8475102, 'Vrouwen_7': 8606405, 'SoortRegio_2': 'Land      ', 'GeboorteRelatief_25': 9}, {'WijkenEnBuurten': 'Aa en Hunze', 'Codering_3': 'GM1680', 'Mannen_6': 12603, 'Vrouwen_7': 12683, 'SoortRegio_2': 'Gemeente  ', 'GeboorteRelatief_25': 6}]

df = pandas.DataFrame(d)
a = altair.Data(df)

$ python ./test.py
Traceback (most recent call last):
  File "./t_altair_schema.py", line 5, in <module>
    a = altair.Data(df)
  File "/home/paulm/.local/lib/python3.8/site-packages/altair/vegalite/v3/schema/core.py", line 3741, in __init__
    super(Data, self).__init__(*args, **kwds)
  File "/home/paulm/.local/lib/python3.8/site-packages/altair/utils/schemapi.py", line 154, in __init__
    self.to_dict(validate=True)
  File "/home/paulm/.local/lib/python3.8/site-packages/altair/utils/schemapi.py", line 302, in to_dict
    raise SchemaValidationError(self, err)
altair.utils.schemapi.SchemaValidationError: <exception str() failed>
```

Somehow the exception can't be turned into a string. I briefly looked at the relevant code in altair.utils.schemapi, but don't immediately see what is going wrong.

This is with Python 3.8.1, altair 3.2.0 on Arch Linux (64-bit)

**Comment by jakevdp** [comment]
Thanks for the report – this only appears to happen with Python 3.8, not with any other supported Py 3.X releases.
