### ISSUE TITLE
DOC: Compilation Errors

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair#1972]
I am having trouble compiling the docs again. 

There seems to be an issue with with [One Dot Per Zipcode](https://altair-viz.github.io/gallery/one_dot_per_zipcode.html#one-dot-per-zipcode) example. 

In the `altair/doc/` directory I ran

```bash
make clean-all
make html
```

Everything was chugging along but then crashed with the following output

```
writing output... [ 12%] gallery/normed_parallel_coordinates
Exception occurred:
  File "/Users/eitanlees/sandbox/open_source/altair-viz/altair/altair/expr/core.py", line 7, in __repr__
    raise ValueError("must use datum.attribute")
ValueError: must use datum.attribute
The full traceback has been saved in /var/folders/dh/ts6jzzjj7pn1_76vh_6vnn6c0000gn/T/sphinx-err-e2vhz5gm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

Following the link to the full traceback I found 

```
Traceback (most recent call last):
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/builders/html.py", line 612, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/writers/html.py", line 58, in translate
    self.document.walkabout(visitor)
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/sphinx/util/docutils.py", line 501, in dispatch_departure
    (method.__name__, node))
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 586, in __unicode__
    ''.join([unicode(c) for c in self.children]),
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 586, in <listcomp>
    ''.join([unicode(c) for c in self.children]),
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 589, in __unicode__
    return self.emptytag()
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 618, in emptytag
    for n, v in self.attlist()])
  File "/Users/eitanlees/miniconda3/lib/python3.7/site-packages/docutils/nodes.py", line 618, in <listcomp>
    for n, v in self.attlist()])
  File "/Users/eitanlees/sandbox/open_source/altair-viz/altair/altair/expr/core.py", line 7, in __repr__
    raise ValueError("must use datum.attribute")
ValueError: must use datum.attribute
```

Not sure if it's something on my end, something with the example, or something with the sphinx extension that is causing the issue. 

Can others compile the docs just fine?

**Comment by jakevdp** [comment]
I've not had any problems compiling the docs. That error happens when the repr of ``alt.datum`` is computed. Maybe something changed in a recent sphinx release that caused it to compute the repr of objects it finds?

**Comment by jakevdp** [comment]
We could probably change the repr to ``"datum"`` –

**Comment by eitanlees** [comment]
In [altair/expr/core.py](https://github.com/altair-viz/altair/blob/master/altair/expr/core.py) I changed
```python
def __repr__(self):
    raise ValueError("must use datum.attribute")
```
to 
```python
def __repr__(self):
    return "datum"
```
and that alleviated the problem.

I am always hesitant to make changes to core code because of unforeseen downstream effects, but is that the change you recommended? If so I can submit a PR right away.

**Comment by jakevdp** [comment]
That solves the docs problem, but if users leave a stray ``alt.datum`` within their chart specification, it will replace an easier-to-debug python error with a more-difficult-to-debug javascript error. I'm not certain raising a ``ValueError`` on ``repr`` is the best solution to this, however...

**Comment by jakevdp** [comment]
That said, now that I think about it, it *is* valid to use ``datum`` by itself in a spec. Here's an example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({'x': range(5)})


alt.Chart(df).transform_calculate(
    datum_ref='datum',
    z='datum.datum_ref.x'
).mark_point().encode(
    x='z:O'
)
```
![visualization - 2020-02-17T065554 698](https://user-images.githubusercontent.com/781659/74664435-8d6b2980-5152-11ea-8fce-0496a6f5384c.png)

I'm not sure why you'd ever want to do it, but experience has shown that Altair users figure out ways to use the grammar that we'd never anticipate :smile:

I think it's probably best to make the change you mention above, to err away from being overly restrictive.
