### ISSUE TITLE
Bug with vegalite?

### ISSUE THREAD

**Issue by ADR777** [altair-viz/altair#2067]
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr  4 22:40:59 2020

@author: a
"""

import altair as alt
alt.renderers.enable('altair_viewer')
# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

chart = alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()

#chart.show()
chart.save('filename.html')

results in the following error since updating to Altair 4.1 

runfile('/home/a/ADR/SPYDER_CODE/untitled0.py', wdir='/home/a/ADR/SPYDER_CODE')
Traceback (most recent call last):

  File "/home/a/ADR/SPYDER_CODE/untitled0.py", line 16, in <module>
    chart = alt.Chart(cars).mark_point().encode(

  File "/home/a/anaconda3/lib/python3.7/site-packages/altair/vegalite/v4/api.py", line 1696, in __init__
    ip="127.0.0.1",

  File "/home/a/anaconda3/lib/python3.7/site-packages/altair/vegalite/v4/schema/core.py", line 17901, in __init__
    super(TopLevelUnitSpec, self).__init__(data=data, mark=mark, autosize=autosize,

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by ADR777** [comment]
I restarted Spyder IDE and this issue was resolved

**Comment by ADR777** [comment]
```
import altair as alt
from vega_datasets import data
from altair_saver import save
import altair_viewer


alt.renderers.enable('altair_viewer')
alt.renderers.enable('html')
```
