### ISSUE TITLE
Error saving SVG chart

### ISSUE THREAD

**Issue by biotemon** [altair-viz/altair#2111]
Hello, I am having problems exporting a chart into SVG format. 

The command I am running is:

`
import altair as alt
from altair_saver import save
alt.renderers.enable('altair_saver')
barplot_4_anvio.save('barplot_4_anvio.svg')
`

The output is 

```
/Users/tito_miniconda/opt/miniconda3/envs/anvio-6.2/lib/vega-cli/node_modules/vega-dataflow/build/vega-dataflow.js:43
  async function asyncCallback(df, callback) {
        ^^^^^^^^


SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tito_miniconda/opt/miniconda3/envs/anvio-6.2/lib/vega-cli/node_modules/vega/build/vega-node.js:6:20)

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-6-ef1792c95abf> in <module>
      1 alt.renderers.enable('altair_saver')
----> 2 barplot_4_anvio.save('barplot_4_anvio.svg')

/usr/local/lib/python3.7/site-packages/altair/vegalite/v4/api.py in save(self, fp, format, override_data_transformer, scale_factor, vegalite_version, vega_version, vegaembed_version, **kwargs)
    474         if override_data_transformer:
    475             with data_transformers.disable_max_rows():
--> 476                 result = save(**kwds)
    477         else:
    478             result = save(**kwds)

/usr/local/lib/python3.7/site-packages/altair/utils/save.py in save(chart, fp, vega_version, vegaembed_version, format, mode, vegalite_version, embed_options, json_kwds, webdriver, scale_factor, **kwargs)
    119             webdriver=webdriver,
    120             scale_factor=scale_factor,
--> 121             **kwargs,
    122         )
    123         if format == "png":

/usr/local/lib/python3.7/site-packages/altair/utils/mimebundle.py in spec_to_mimebundle(spec, format, mode, vega_version, vegaembed_version, vegalite_version, **kwargs)
     58                 "see http://github.com/altair-viz/altair_saver/".format(fmt=format)
     59             )
---> 60         return altair_saver.render(spec, format, mode=mode, **kwargs)
     61     if format == "html":
     62         html = spec_to_html(

/usr/local/lib/python3.7/site-packages/altair_saver/_core.py in render(chart, fmts, mode, embed_options, method, **kwargs)
    255         Saver = _select_saver(method, mode=mode, fmt=fmt)
    256         saver = Saver(spec, mode=mode, embed_options=embed_options, **kwargs)
--> 257         mimebundle.update(saver.mimebundle(fmt))
    258 
    259     return mimebundle

/usr/local/lib/python3.7/site-packages/altair_saver/savers/_saver.py in mimebundle(self, fmts)
     88                 vegalite_version=self._package_versions["vega-lite"],
     89             )
---> 90             bundle[mimetype] = self._serialize(fmt, "mimebundle")
     91         return bundle
     92 

/usr/local/lib/python3.7/site-packages/altair_saver/savers/_node.py in _serialize(self, fmt, content_type)
    119             return self._vg2png(spec)
    120         elif fmt == "svg":
--> 121             return self._vg2svg(spec)
    122         elif fmt == "pdf":
    123             return self._vg2pdf(spec)

/usr/local/lib/python3.7/site-packages/altair_saver/savers/_node.py in _vg2svg(self, spec)
     95             [vg2svg, *(self._vega_cli_options or [])],
     96             input=vg_json,
---> 97             stderr_filter=self._stderr_filter,
     98         ).decode()
     99 

/usr/local/lib/python3.7/site-packages/altair_saver/_utils.py in check_output_with_stderr(cmd, shell, input, stderr_filter)
    202             check=True,
    203             stdout=subprocess.PIPE,
--> 204             stderr=subprocess.PIPE,
    205         )
    206     except subprocess.CalledProcessError as err:

/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    510         if check and retcode:
    511             raise CalledProcessError(retcode, process.args,
--> 512                                      output=stdout, stderr=stderr)
    513     return CompletedProcess(process.args, retcode, stdout, stderr)
    514 

CalledProcessError: Command '['/Users/tito_miniconda/opt/miniconda3/envs/anvio-6.2/bin/vg2svg']' returned non-zero exit status 1.

```

Any suggestions on how to fix this?

Thank you

**Comment by jakevdp** [comment]
You are hitting this issue: https://github.com/altair-viz/altair_saver/issues/13

The fix is still not clear (it's something to do with how npm packages are installed). The easiest approach would be to use the selenium saver instead; see the requirements at https://github.com/altair-viz/altair_saver#selenium
