### ISSUE TITLE
latest altairplot sphinx extension uses deprecated methods

### ISSUE THREAD

**Issue by bmorris3** [altair-viz/altair#2473]
Thanks for contributing to this useful tool! I'm using the altairplot sphinx directive, which is causing an error on readthedocs ([log](https://readthedocs.org/projects/owls/builds/13944611/)) similar to sphinx-doc/sphinx#7747, 

```python
Running Sphinx v4.0.2
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/owls/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/owls/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 243, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/owls/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 400, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/owls/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 433, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/owls/envs/latest/lib/python3.7/site-packages/altair/sphinxext/altairplot.py", line 327, in setup
    app.add_stylesheet("altair-plot.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/owls/envs/latest/lib/python3.7/site-packages/altair/sphinxext/altairplot.py", line 327, in setup
    app.add_stylesheet("altair-plot.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-uu3r76yw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The fix may be as simple as replacing
```
app.add_stylesheet("altair-plot.css")
```
with 
```
app.add_css_file("altair-plot.css")
```

I see that this change was made in [this commit](https://github.com/altair-viz/altair/commit/c6d7f581f357fa5d93066d18fa5842f016fc683e) but there hasn't been a new release since. Is a new release coming soon? Thanks!

**Comment by bmorris3** [comment]
Fixing `sphinx==1.8` seems to be a viable temporary fix in my case.

**Comment by joelostblom** [comment]
There has now been a new release (4.2.0) of Altair including the latest version of the sphinx extension

**Comment by bmorris3** [comment]
Thanks @joelostblom!
