### ISSUE TITLE
New version of jsonschema crash transform_fold

### ISSUE THREAD

**Issue by rikardn** [altair-viz/altair#2496]
The snippet below works fine with jsonschema 3.20, but crash with jsonschema 4.0.1:

```python
import pandas as pd
from io import StringIO

df = pd.read_table(StringIO("""
TVCL      TVV
0.005298  1.30730
0.006048  1.38692
0.005624  1.53224
0.005771  1.40115
0.005932  1.42119
"""), sep='\s+')

import altair as alt

base = (
    alt.Chart(df)
    .transform_fold(list(df.columns), as_=['key_x', 'value_x'])
)
```

this is the error:

```
Traceback (most recent call last):

  File "<ipython-input-8-50da994c20c5>", line 2, in <module>
    alt.Chart(df)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 1159, in transform_fold
    return self._add_transform(core.FoldTransform(fold=fold, **{"as": as_}))

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/altair/vegalite/v4/schema/core.py", line 18192, in __init__
    super(FoldTransform, self).__init__(fold=fold, **kwds)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/altair/vegalite/v4/schema/core.py", line 17975, in __init__
    super(Transform, self).__init__(*args, **kwds)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/altair/utils/schemapi.py", line 176, in __init__
    self.to_dict(validate=True)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/altair/utils/schemapi.py", line 337, in to_dict
    self.validate(result)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/altair/utils/schemapi.py", line 442, in validate
    return jsonschema.validate(instance, schema, resolver=resolver)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 965, in validate
    error = exceptions.best_match(validator.iter_errors(instance))

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/exceptions.py", line 354, in best_match
    best = next(errors, None)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 224, in iter_errors
    for error in errors:

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/_validators.py", line 295, in ref
    yield from validator.descend(instance, resolved)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 240, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 224, in iter_errors
    for error in errors:

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/_validators.py", line 329, in properties
    yield from validator.descend(

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 240, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 224, in iter_errors
    for error in errors:

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/_validators.py", line 76, in items
    yield from validator.descend(

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 240, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 214, in iter_errors
    scope = id_of(_schema)

  File "/home/devel/pharmpy/.tox/py39/lib/python3.9/site-packages/jsonschema/validators.py", line 90, in _id_of
    return schema.get("$id", "")

AttributeError: 'list' object has no attribute 'get'
```

**Comment by jakevdp** [comment]
Thanks for the report! It looks like jsonschema 4.0 is incompatible with the schema format produced by Vega-Lite. Here is a minimal example of a schema that works with jsonschema 3.X, but fails with jsonschema 4.0.1:
```python
import jsonschema
instance = ['A', 'B']
schema = {
  "type": "array",
  "items": [{"type": "string"}, {"type": "string"}]
}
jsonschema.validate(instance, schema)
```
I'm not sure whether this is a bug in jsonschema, or a reflection of some documented change to defaults in the jsonschema package. But for the time being, I'd suggest using jsonschema 3.X with the Altair package.

**Comment by rikardn** [comment]
Thanks for having a look. I filed an issue upstream: https://github.com/Julian/jsonschema/issues/852

**Comment by Julian** [comment]
(Hello, jsonschema author here, I see the issue I just closed came originally from altair, so just checking in)

I don't see in a quick grep where in altair these schemas are assembled otherwise I'd be happy to help, but yeah the difference you notice is because the schema isn't [setting $schema to declare what version it's written for](https://json-schema.org/understanding-json-schema/reference/schema.html#schema). So in 3.2.0, you're getting a default version (draft 7) and in 4.0 you're still getting a default version (now draft 2020-12, where what you have there is [now spelled using `prefixItems`](https://json-schema.org/draft/2020-12/release-notes.html)). Definitely worth considering making sure you have `$schema` present, even if you intend to stick with draft 7 for now.

```python
schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": [{"type": "string"}, {"type": "string"}]
}
```

would have consistent behavior across versions (as would using `jsonschema.validators.Draft7Validator` directly).

Hope that helps.

**Comment by jakevdp** [comment]
Thanks for the info – we do set the schema version explicitly: https://github.com/altair-viz/altair/blob/8ff06cfbbfb470aba6798999c61128be398c4996/altair/vegalite/v4/schema/vega-lite-schema.json#L3

I suspect there must be some kind of issue with the way we call the validation API, which is here: https://github.com/altair-viz/altair/blob/8ff06cfbbfb470aba6798999c61128be398c4996/altair/utils/schemapi.py#L434-L442

Perhaps relevant, the `$schema` is set within the `resolver` schema, rather than the schema passed to `validate`.
