### ISSUE TITLE
Sphinx autodoc can't find `parameter`

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2945]
It seems sphinx autodoc is trying to include `parameter` in the autogenerated docs, but failing cause altair does not have anything names `parameter` (since we changed the name to `param`). However, I can't find where in the code this is detected.

```
WARNING: autodoc: failed to import function 'parameter' from module 'altair'; the following exception was raised:
Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/altdev/lib/python3.11/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'altair' has no attribute 'parameter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/altdev/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/miniconda3/envs/altdev/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/miniconda3/envs/altdev/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/miniconda3/envs/altdev/lib/python3.11/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: parameter
```

**Comment by binste** [comment]
I cannot reproduce this on the current master branch when running:
```bash
cd doc
make clean
make html
```

Any additional infos that could help debugging?

**Comment by joelostblom** [comment]
Thanks @binste, I can confirm that this was a local issue (I think something with my env), closing this.
