### ISSUE TITLE
altair viz generating JSON that fails in vg2svg

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#299]
Here's a completely cut down version that has the same problem:

VL: 
```
{
  "mark": "point",
  "data": {
    "values": [
      {
        "engine": "Gunrock",
        "algorithm": "BFS",
        "num_gpus": 2,
        "elapsed": 25.94273567199707,
        "dataset": "kron_g500-logn21",
        "m_teps": 7018.599609375,
        "gpuinfo.name": "Tesla K80"
      }
    ]
  },
  "transform": {
    "filter": "(datum.dataset==u'kron_g500-logn21')"
  },
  "encoding": {
    "y": {
      "field": "m_teps",
      "scale": {
        "type": "log"
      },
      "type": "quantitative",
      "axis": {
        "title": "MTEPS"
      }
    },
    "x": {
      "field": "num_gpus",
      "type": "nominal",
      "axis": {
        "title": "Number of GPUs"
      }
    }
  }
}
```

Vega: 
```
{
  "width": 1,
  "height": 1,
  "padding": "auto",
  "data": [
    {
      "name": "source",
      "values": [
        {
          "engine": "Gunrock",
          "algorithm": "BFS",
          "num_gpus": 2,
          "elapsed": 25.94273567199707,
          "dataset": "kron_g500-logn21",
          "m_teps": 7018.599609375,
          "gpuinfo.name": "Tesla K80"
        }
      ],
      "format": {
        "type": "json",
        "parse": {
          "m_teps": "number"
        }
      },
      "transform": [
        {
          "type": "filter",
          "test": "datum[\"m_teps\"] !== null && !isNaN(datum[\"m_teps\"])"
        },
        {
          "type": "filter",
          "test": "(datum.dataset==u'kron_g500-logn21')"
        },
        {
          "type": "filter",
          "test": "datum[\"m_teps\"] > 0"
        }
      ]
    },
    {
      "name": "layout",
      "source": "source",
      "transform": [
        {
          "type": "aggregate",
          "summarize": [
            {
              "field": "num_gpus",
              "ops": [
                "distinct"
              ]
            }
          ]
        },
        {
          "type": "formula",
          "field": "width",
          "expr": "(datum[\"distinct_num_gpus\"] + 1) * 21"
        },
        {
          "type": "formula",
          "field": "height",
          "expr": "200"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "root",
      "type": "group",
      "from": {
        "data": "layout"
      },
      "properties": {
        "update": {
          "width": {
            "field": "width"
          },
          "height": {
            "field": "height"
          }
        }
      },
      "marks": [
        {
          "name": "marks",
          "type": "symbol",
          "from": {
            "data": "source"
          },
          "properties": {
            "update": {
              "x": {
                "scale": "x",
                "field": "num_gpus"
              },
              "y": {
                "scale": "y",
                "field": "m_teps"
              },
              "size": {
                "value": 30
              },
              "shape": {
                "value": "circle"
              },
              "strokeWidth": {
                "value": 2
              },
              "opacity": {
                "value": 0.7
              },
              "stroke": {
                "value": "#4682b4"
              },
              "fill": {
                "value": "transparent"
              }
            }
          }
        }
      ],
      "scales": [
        {
          "name": "x",
          "type": "ordinal",
          "domain": {
            "data": "source",
            "field": "num_gpus",
            "sort": true
          },
          "bandSize": 21,
          "round": true,
          "points": true,
          "padding": 1
        },
        {
          "name": "y",
          "type": "log",
          "domain": {
            "data": "source",
            "field": "m_teps"
          },
          "rangeMin": 200,
          "rangeMax": 0,
          "round": true,
          "nice": true,
          "zero": true
        }
      ],
      "axes": [
        {
          "type": "x",
          "scale": "x",
          "grid": false,
          "ticks": 5,
          "title": "Number of GPUs",
          "properties": {
            "labels": {
              "text": {
                "template": "{{ datum[\"data\"] | truncate:25 }}"
              },
              "angle": {
                "value": 270
              },
              "align": {
                "value": "right"
              },
              "baseline": {
                "value": "middle"
              }
            }
          }
        },
        {
          "type": "y",
          "scale": "y",
          "format": "s",
          "grid": true,
          "layer": "back",
          "title": "MTEPS"
        }
      ]
    }
  ]
}
```

Error:

```
[Vega Err] PARSE DATA FAILED: source Error: Line 1: Unexpected string
[Vega Err] Error: Line 1: Unexpected string
[Vega Err] Error: Line 1: Unexpected string
/Users/jowens/Documents/working/vega/bin/vg2svg:66
    if (err) { throw err; }
               ^

Error: Line 1: Unexpected string
    at throwError (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1441:19)
    at throwUnexpected (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1481:11)
    at expect (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1508:11)
    at parseGroupExpression (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1688:7)
    at parsePrimaryExpression (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1702:18)
    at parseLeftHandSideExpressionAllowCall (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1804:14)
    at parsePostfixExpression (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1828:18)
    at parseUnaryExpression (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1856:18)
    at parseBinaryExpression (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:1945:14)
    at parseConditionalExpression (/Users/jowens/Documents/working/vega/node_modules/vega-expression/src/parser.js:2000:14)
```

Altair code that's generating this:
```
for dataset in datasets:
    chart[dataset] = Chart(df).mark_point().encode(
        x=X('num_gpus:N',
            axis=Axis(
                title='Number of GPUs',
            ),
            ),
        column=Column('[gpuinfo.name]:N',
                      axis=Axis(
                          title='GPU',
                          orient='top',
                      )
                      ),
        row=Row('algorithm:N',
                axis=Axis(
                    title='Primitive',
                )
                ),
        y=Y('m_teps',
            axis=Axis(
                title='MTEPS',
            ),
            scale=Scale(type='log'),
            ),
        shape=Shape('engine:N',
                    legend=Legend(
                        title='Engine',
                    ),
                    ),
        color=Color('engine:N',
                    legend=Legend(
                        title='Engine',
                    ),
                    ),
    ).transform_data(
        filter=(expr.df.dataset == dataset)
    )
```

For completeness, I'm putting the full (vega-lite) JSON here: http://tinyurl.com/jyhvuz3

**Comment by jowens** [comment]
@kanitw might this be an issue that the Vega/VL team might be able to clarify?

**Comment by jowens** [comment]
@domoritz help a brother out?

**Comment by domoritz** [comment]
The filter looks odd `"filter": "(datum.dataset==u'kron_g500-logn21')"` should be `"filter": "(datum.dataset=='kron_g500-logn21')"` (no `u`). This seems to be an altair issue with unicode strings.

**Comment by jowens** [comment]
Yes! That fixed it. For the record, that filter came from a `df.unique()` call, which I've now replaced with:

```
datasets = [x.encode('ascii', 'ignore') for x in df.dataset.unique()]
for dataset in datasets:
    ...
```

Thanks, @domoritz. You're awesome.
