### ISSUE TITLE
Extension error (sphinxext.altairgallery): `isotype_emoji.svg`

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#3002]
I'm not able to successfully build the docs with default settings (on windows).

This is the error I'm facing:
```
-> saving C:\Notebooks\mattijn\altair\doc\_images\isotype_emoji.svg

Extension error (sphinxext.altairgallery):
Handler <function main at 0x000001DE2270E8B0> for event 'builder-inited' threw an exception (exception: 'charmap' codec can't encode character '\U0001f404' in position 2488: character maps to <undefined>)
```
The  `'\U0001f404'` is the 🐄 emoji, so it is something specific to this chart only. I remember we switched to svg-rendering for this chart specifically for this reason as it was not able to render when using `.png`.

But when I define this line: https://github.com/altair-viz/altair/blob/master/tests/examples_arguments_syntax/__init__.py#L5
as `SVG_EXAMPLES = {}`, so forcing png only for all examples, it gives me still a reasonable png thumbnail for isotype_emoji (again, on windows):
![image](https://user-images.githubusercontent.com/5186265/228644785-fdca7637-013d-4db9-90f4-f01ead608dee.png)

**Comment by joelostblom** [comment]
On PopOS/Ubuntu, I see this warning both with and without the change you suggested (docs build fine except the thumbnail for this chart which fails to render in both cases):

```
ERROR Error: Failed to locate text in SVG:

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100" height="100">
    <text x="20" y="50" font-size="45" font-family="sans-serif">🐄</text>
</svg>
["Group(Group { id: \"\", transform: Transform { a: 1.0, b: 0.0, c: 0.0, d: 1.0, e: 0.0, f: 0.0 }, opacity: NormalizedF64(FiniteF64(1.0)), blend_mode: Normal, isolate: false, clip_path: None, mask: None, filters: [], filter_fill: None, filter_stroke: None, enable_background: None })"]
    at Object.sg.textMetrics.width (<anon>:14:30)
    at Be (https://cdn.skypack.dev/-/vega-scenegraph@v4.9.4-Rfd7OGmaS9T7w10Fz4Yx/dist=es2020,mode=imports,min/optimized/vega-scenegraph.js:1:29874)
    at $ (https://cdn.skypack.dev/-/vega-view-transforms@v4.5.8-jtX42Ax7WNjhu4BmY9kH/dist=es2020,mode=imports,min/optimized/vega-view-transforms.js:1:1587)
    at https://cdn.skypack.dev/-/vega-view-transforms@v4.5.8-jtX42Ax7WNjhu4BmY9kH/dist=es2020,mode=imports,min/optimized/vega-view-transforms.js:1:1277
    at Array.forEach (<anonymous>)
    at gt.transform (https://cdn.skypack.dev/-/vega-view-transforms@v4.5.8-jtX42Ax7WNjhu4BmY9kH/dist=es2020,mode=imports,min/optimized/vega-view-transforms.js:1:1258)
    at gt.evaluate (https://cdn.skypack.dev/-/vega-dataflow@v5.7.4-DrCzG6Luqf74SfPN5Hxw/dist=es2020,mode=imports,min/optimized/vega-dataflow.js:1:15456)
    at gt.run (https://cdn.skypack.dev/-/vega-dataflow@v5.7.4-DrCzG6Luqf74SfPN5Hxw/dist=es2020,mode=imports,min/optimized/vega-dataflow.js:1:15313)
    at ne.Jt [as evaluate] (https://cdn.skypack.dev/-/vega-dataflow@v5.7.4-DrCzG6Luqf74SfPN5Hxw/dist=es2020,mode=imports,min/optimized/vega-dataflow.js:1:12100)
    at ne.evaluate (https://cdn.skypack.dev/-/vega-view@v5.11.0-qj2ShFtxO2P3GWqTy2DZ/dist=es2020,mode=imports,min/optimized/vega-view.js:2:1621)
```

**Comment by jonmmease** [comment]
Looks like this might be a VlConvert issue, but I'm not sure what would have changed since it was working previously. Maybe the update to Vega-Lite 5 shifted something?
