### ISSUE TITLE
Local data server breaks with transition to altair 5.0.0

### ISSUE THREAD

**Issue by caleb-lindgren** [altair-viz/altair#3048]
In order to handle some large datasets, I've been using the local data server option described [here](https://altair-viz.github.io/user_guide/large_datasets.html#local-data-server) in the latest documentation. However, when I run this code with altair 5.0.0, I get a `NoSuchEntryPoint` exception:

```
Python 3.10.11 (main, May  9 2023, 12:49:29) [GCC 13.1.1 20230429] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import altair as alt
>>> alt.data_transformers.enable('data_server')
Traceback (most recent call last):
  File "/home/caleb/.pyenv/versions/3.10.11/lib/python3.10/site-packages/altair/utils/plugin_registry.py", line 155, in _enable
    (ep,) = [
ValueError: not enough values to unpack (expected 1, got 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/caleb/.pyenv/versions/3.10.11/lib/python3.10/site-packages/altair/utils/plugin_registry.py", line 194, in enable
    return PluginEnabler(self, name, **options)
  File "/home/caleb/.pyenv/versions/3.10.11/lib/python3.10/site-packages/altair/utils/plugin_registry.py", line 41, in __init__
    self.registry._enable(name, **options)
  File "/home/caleb/.pyenv/versions/3.10.11/lib/python3.10/site-packages/altair/utils/plugin_registry.py", line 164, in _enable
    raise NoSuchEntryPoint(self.entry_point_group, name) from err
altair.utils.plugin_registry.NoSuchEntryPoint: No 'data_server' entry point found in group 'altair.vegalite.v5.data_transformer'
>>>
```
If I downgrade to altair version 4.2.2 the same code works with no issues.

I have the latest version of altair-data-server (0.4.1).

I get the same results when running this from jupyter-lab, I just figured demonstrating it in the command line would be a simpler example.

**Comment by mattijn** [comment]
Thank you for the report. `altair_data_server` is indeed not yet supported by Altair version 5. The best thing for now is that we can add a note to the documentation that `altair_data_server` does not yet support Altair 5.

If you are using large datasets including aggregations in your Altair specification than the recent developments of VegaFusion might be of interest to you as well, see https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion and https://vegafusion.io/ for more info on this.

Again, thanks for the report!

**Comment by joelostblom** [comment]
Based on https://github.com/hex-inc/vegafusion/issues/309, it seems like the VegaFusion widget renderer covers most use cases that the data-server was used for. It still makes sense to update the data-server to support v5 for compatibility reasons, but maybe we should clearly mark it as being in maintenance mode and direct people to use the VegaFusion widget renderer more explicitly in the docs?

**Comment by dangotbanned** [comment]
https://github.com/altair-viz/altair_data_server was archived on **Apr 9, 2024**, but is still recommended in the [User Guide](https://altair-viz.github.io/user_guide/large_datasets.html#passing-data-by-url).

We should update the docs to reflect @joelostblom's comment https://github.com/vega/vegafusion/issues/309#issuecomment-2496100117 and removed the section IMO

> As of now Vegafusion has indeed completely replace the altair data server 🎉 🚀
