### ISSUE TITLE
Boolean numpy-backed type fails when pyarrow is installed in env

### ISSUE THREAD

**Issue by pavlomuts** [altair-viz/altair#3205]
I am using altair with `pandas `dataframe with numpy-backed types and I using `streamlit `to visualize it. `streamlit` has `pyarrow ` as dependency and it turns out that datatype inference using pyarrow fails for nullable boolean of pandas dtype. Small (unrealistic) example reproduces the error:

```python
import altair as alt
import pandas as pd

data = pd.DataFrame(
    {
        "x": pd.Series([1, 3, 5, 1, 3, 5]),
        "y": pd.Series([2, 4, 6, 2, 4, 6]),
        "flag": pd.Series([True, False, True, False, True, None], dtype="boolean"),
    }
)

chart = alt.Chart(data).mark_circle().encode(x="x", y="y", color="flag")
``` 

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\ad\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\ad\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\ad\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\ad\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\ad\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ad\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\ad\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "test.py", line 18, in <module>
    chart.save(file, format="html")
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\vegalite\v5\api.py", line 1066, in save
    result = save(**kwds)
             ^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\save.py", line 189, in save
    perform_save()
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\save.py", line 127, in perform_save
    spec = chart.to_dict(context={"pre_transform": False})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\vegalite\v5\api.py", line 2695, in to_dict
    return super().to_dict(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\vegalite\v5\api.py", line 903, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 965, in to_dict
    result = _todict(
             ^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 477, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 477, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 473, in _todict
    return obj.to_dict(validate=False, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 965, in to_dict
    result = _todict(
             ^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 477, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 477, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\schemapi.py", line 473, in _todict
    return obj.to_dict(validate=False, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\vegalite\v5\schema\channels.py", line 34, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get('data', None))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\core.py", line 590, in parse_shorthand
    attrs["type"] = infer_vegalite_type_for_dfi_column(column)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\altair\utils\core.py", line 639, in infer_vegalite_type_for_dfi_column
    kind = column.dtype[0]
           ^^^^^^^^^^^^
  File "properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\pandas\core\interchange\column.py", line 128, in dtype
    return self._dtype_from_pandasdtype(dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad\AppData\Local\pypoetry\Cache\virtualenvs\cero-bIEndBiR-py3.11\Lib\site-packages\pandas\core\interchange\column.py", line 147, in _dtype_from_pandasdtype
    byteorder = dtype.byteorder
                ^^^^^^^^^^^^^^^
AttributeError: 'BooleanDtype' object has no attribute 'byteorder'
``` 

And my environment:
```
altair                    5.1.1        Vega-Altair: A declarative statistical visualization library for Python.
astroid                   2.15.8       An abstract syntax tree for Python with inference support.
attrs                     23.1.0       Classes Without Boilerplate
black                     23.9.1       The uncompromising code formatter.
blinker                   1.6.2        Fast, simple object-to-object and broadcast signaling
boltons                   20.2.1       When they're not builtins, they're boltons.
cachetools                5.3.1        Extensible memoizing collections and decorators
certifi                   2023.7.22    Python package for providing Mozilla's CA Bundle.
cffi                      1.15.1       Foreign Function Interface for Python calling C code.
charset-normalizer        3.2.0        The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
click                     8.1.7        Composable command line interface toolkit
colorama                  0.4.6        Cross-platform colored terminal text.
cryptography              41.0.4       cryptography is a package which provides cryptographic recipes and primitives to Python developers.
datargs                   0.12.0       Declarative, type-safe command line argument parsers from dataclasses and attrs classes
dill                      0.3.7        serialize all of Python
flake8                    6.1.0        the modular source code checker: pep8 pyflakes and co
gitdb                     4.0.10       Git Object Database
gitpython                 3.1.37       GitPython is a Python library used to interact with Git repositories
greenlet                  2.0.2        Lightweight in-process concurrent programming
idna                      3.4          Internationalized Domain Names in Applications (IDNA)
importlib-metadata        6.8.0        Read metadata from Python packages
iniconfig                 2.0.0        brain-dead simple config-ini parsing
isort                     5.12.0       A Python utility / library to sort Python imports.
jinja2                    3.1.2        A very fast and expressive template engine.
joblib                    1.3.2        Lightweight pipelining with Python functions
jsonschema                4.19.1       An implementation of JSON Schema validation for Python
jsonschema-specifications 2023.7.1     The JSON Schema meta-schemas and vocabularies, exposed as a Registry
lazy-object-proxy         1.9.0        A fast and thorough lazy object proxy.
markdown-it-py            3.0.0        Python port of markdown-it. Markdown parsing, done right!
markupsafe                2.1.3        Safely add untrusted strings to HTML/XML markup.
mccabe                    0.7.0        McCabe checker, plugin for flake8
mdurl                     0.1.2        Markdown URL utilities
mypy                      1.5.1        Optional static typing for Python
mypy-extensions           1.0.0        Type system extensions for programs checked with the mypy type checker.
networkx                  3.1          Python package for creating and manipulating graphs and networks
numpy                     1.26.0       Fundamental package for array computing in Python
oracledb                  1.4.1        Python interface to Oracle Database
packaging                 23.1         Core utilities for Python packages
pandas                    2.1.1        Powerful data structures for data analysis, time series, and statistics
pathspec                  0.11.2       Utility library for gitignore style pattern matching of file paths.
pillow                    9.5.0        Python Imaging Library (Fork)
platformdirs              3.10.0       A small Python package for determining appropriate platform-specific dirs, e.g. a "user data dir".
pluggy                    1.3.0        plugin and hook calling mechanisms for python
protobuf                  4.24.3
pyarrow                   13.0.0       Python library for Apache Arrow
pycodestyle               2.11.0       Python style guide checker
pycparser                 2.21         C parser in Python
pydeck                    0.8.0        Widget for deck.gl maps
pyflakes                  3.1.0        passive checker of Python programs
pygments                  2.16.1       Pygments is a syntax highlighting package written in Python.
pylint                    2.17.6       python code static checker
pytest                    7.4.2        pytest: simple powerful testing with Python
python-dateutil           2.8.2        Extensions to the standard Python datetime module
pytz                      2023.3.post1 World timezone definitions, modern and historical
pyyaml                    6.0.1        YAML parser and emitter for Python
referencing               0.30.2       JSON Referencing + Python
refurb                    1.21.0       A tool for refurbish and modernize Python codebases
requests                  2.31.0       Python HTTP for Humans.
rich                      13.5.3       Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
rpds-py                   0.10.3       Python bindings to Rust's persistent data structures (rpds)
ruff                      0.0.291      An extremely fast Python linter, written in Rust.
scipy                     1.11.2       Fundamental algorithms for scientific computing in Python
six                       1.16.0       Python 2 and 3 compatibility utilities
smmap                     5.0.1        A pure Python implementation of a sliding window memory map manager
snakeviz                  2.2.0        A web-based viewer for Python profiler output
sqlalchemy                2.0.21       Database Abstraction Library
streamlit                 1.27.0       A faster way to build and share data apps
tabulate                  0.9.0        Pretty-print tabular data
tenacity                  8.2.3        Retry code until it succeeds
toml                      0.10.2       Python Library for Tom's Obvious, Minimal Language
tomlkit                   0.12.1       Style preserving TOML library
toolz                     0.12.0       List processing tools and functional utilities
tornado                   6.3.3        Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
typing-extensions         4.8.0        Backported and Experimental Type Hints for Python 3.8+
tzdata                    2023.3       Provider of IANA time zone data
tzlocal                   5.0.1        tzinfo object for the local timezone
urllib3                   2.0.5        HTTP library with thread-safe connection pooling, file post, and more.
validators                0.22.0       Python Data Validation for Humans™
watchdog                  3.0.0        Filesystem events monitoring
wrapt                     1.15.0       Module for decorators, wrappers and monkey patching.
xlsxwriter                3.1.5        A Python module for creating Excel XLSX files.
yamllint                  1.32.0       A linter for YAML files.
zipp                      3.17.0       Backport of pathlib-compatible object wrapper for zip files
``` 
Thank you for taking a looking and for making such a great tool!

**Comment by jonmmease** [comment]
Thanks for the report @pavlomuts. This looks like something we'll need to report upstream to pandas and work around in Altair. I'll try to take a closer look soon.

**Comment by jonmmease** [comment]
Reported upstream in https://github.com/pandas-dev/pandas/issues/55332 and worked around in #3210. We should be able to get this into the 5.1.2 release next week.

A workaround in the meantime is to specify the encoding type of the boolean column explicitly (e.g. for the default of nominal encoding use `color="flag:N"`):

```python
chart = alt.Chart(data).mark_circle().encode(x="x", y="y", color="flag:N")
```
