### ISSUE TITLE
adding other fields to Chart object, KeyError, how to do this non-manually

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#361]
I wanted to add `height`, `width`, and `encoding.tooltip` elements to my Altair object. These aren't in Altair currently (correct me if I'm wrong). So basically I'm having to do things manually, because if I add a tooltip via `chart.to_html` after adding the above elements to my object, I get a `KeyError` (see error message below). It would be nice if this could be done more elegantly (please let me know if I'm missing something!).

As it is, I'm basically having to write HTML manually, which isn't in anyone's best interest:

```python
    with open(os.path.join(outputdir, title + '.html'), 'w') as f:
        spec = chart.to_dict()
        spec['height'] = 750
        spec['width'] = 1213
        spec['encoding']['tooltip'] = {"field": "Model", "type": "nominal"}
        f.write(template.format(spec=json.dumps(spec), title=title))
```

Instead of the last line, I would have preferred `f.write(chart.from_json(spec_str).to_html(title=title, template=template))`.

I'm attaching my template at the very bottom for posterity, because it took me many tries to figure it out.

```
Traceback (most recent call last):
  File "./nvperf.py", line 182, in <module>
    f.write(chart.from_json(spec_str).to_html(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/schema/baseobject.py", line 162, in from_json
    return cls.from_dict(json.loads(spec))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/api.py", line 479, in from_dict
    return super(Chart, cls).from_dict(spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/schema/baseobject.py", line 146, in from_dict
    return FromDict().clsvisit(cls, dct)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 24, in clsvisit
    return method(obj, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 180, in _clsvisit_with_data
    obj = self.clsvisit_BaseObject(cls, dct)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 172, in clsvisit_BaseObject
    obj.set_trait(prop, self.visit(subtrait, val))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 18, in visit
    return method(obj, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 204, in visit_Instance
    return self.clsvisit(trait.klass, dct)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 24, in clsvisit
    return method(obj, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/altair/utils/visitors.py", line 171, in clsvisit_BaseObject
    subtrait = obj.traits()[prop]
KeyError: u'tooltip'
```

```python
template = """<!DOCTYPE html>
<html>
<head>
  <!-- Import Vega 3 & Vega-Lite 2 js (does not have to be from cdn) -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.0-rc4/vega.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.0-beta.10/vega-lite.js"></script>
  <!-- Import vega-embed -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/3.0.0-beta.19/vega-embed.js"></script>
  <title>{title}</title>

  <style media="screen">
    /* Add space between vega-embed links */
    /* http://vega.github.io/vega-tutorials/airports/ */
    .vega-embed .vega-actions a {{
      margin-left: 1em;
      visibility: hidden;
    }}
    .vega-embed:hover .vega-actions a {{
      visibility: visible;
    }}
  </style>
</head>
<body>

<div id="vis"></div>

<script type="text/javascript">
  var opt = {{
    "mode": "vega-lite",
  }};
  vega.embed('#vis', {spec}, opt);
</script>
</body>
</html>"""
```

**Comment by jakevdp** [comment]
That is not supported in the Vega-Lite 1.2 schema, which is what Altair is allowed to export. When we release Altair 2.0, it will be allowed to set these additional arguments that are allowed by the Vega-Lite 1.2 schema.

**Comment by jowens** [comment]
Got it. Thanks @jakevdp.
