### ISSUE TITLE
Sphinx build error

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair#590]
I was trying to compile the new changes to the docs. I did `make clean` then `make html` and got an error. The full trace back is 

```
# Sphinx version: 1.7.1
# Python version: 3.6.4 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/eitanlees/sandbox/open_source/altair/altair/sphinxext/altairgallery.py", line 237, in main
    save_example_pngs(examples, image_dir)
  File "/Users/eitanlees/sandbox/open_source/altair/altair/sphinxext/altairgallery.py", line 129, in save_example_pngs
    chart.savechart(image_file)
  File "/Users/eitanlees/sandbox/open_source/altair/altair/vegalite/v2/api.py", line 333, in savechart
    utils.save_spec(self.to_dict(), fp, format=format, **kwargs)
  File "/Users/eitanlees/sandbox/open_source/altair/altair/utils/headless.py", line 136, in save_spec
    spec, mode)
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 650, in execute_async_script
    'args': converted_args})['value']
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=65.0.3325.162)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

**Comment by jakevdp** [comment]
Yes, you need to install ``selenium`` and ``chrome_driver`` to build the docs (this is in order to generate thumbnails for all the example images).

On my computer, I did this with:

```
$ conda install selenium
$ brew install chrome_driver
```

Up until this past Tuesday, you could install chrome_driver with conda, but chrome did an update that broke the version available on conda 😢

**Comment by eitanlees** [comment]
I got it working. I will outline my hang ups if anyone else has an issue. First of all it's 

```
$ brew install chromedriver
```

After the installation I was still having trouble but that's because the `chromedriver` command was pointing to my conda path. 

```
$ which chromedriver
/Users/eitanlees/anaconda3/bin/chromedriver
```

So I uninstalled 

```
conda uninstall chromedriver
```

and now things are working.

**Comment by jakevdp** [comment]
great!
