### ISSUE TITLE
problem to install @jupyterlab/vega3-extension

### ISSUE THREAD

**Issue by ijlyttle** [altair-viz/altair#669]
Hi,

This may not be the best place for this issue, but I thought I would start here given the JupyterLab installation instructions [[link](https://altair-viz.github.io/getting_started/installation.html#installing-altair-with-jupyterlab)]:

```
$ jupyter labextension install @jupyterlab/vega3-extension
```

When I try this, I get an error that suggests that there is a repository (jupyterlab/vega3-extension) that does not exist (output below).

Can you point me in the right direction to sort this out?

Thanks!

```
> /usr/local/bin/npm pack @jupyterlab/vega3-extension
npm ERR! git clone git@github.com:jupyterlab/vega3-extension Cloning into bare repository '/var/root/.npm/_git-remotes/git-github-com-jupyterlab-vega3-extension-50bd1090'...
npm ERR! git clone git@github.com:jupyterlab/vega3-extension ERROR: Repository not found.
npm ERR! git clone git@github.com:jupyterlab/vega3-extension fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:jupyterlab/vega3-extension 
npm ERR! git clone git@github.com:jupyterlab/vega3-extension Please make sure you have the correct access rights
npm ERR! git clone git@github.com:jupyterlab/vega3-extension and the repository exists.
npm ERR! addLocal Could not install jupyterlab/vega3-extension
npm ERR! Error: ENOENT, stat 'jupyterlab/vega3-extension'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 17.4.0
npm ERR! command "node" "/usr/local/bin/npm" "pack" "@jupyterlab/vega3-extension"
npm ERR! cwd /private/tmp/tmpi5q4wxwd
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path jupyterlab/vega3-extension
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/tmp/tmpi5q4wxwd/npm-debug.log
npm ERR! not ok code 0

Errored, use --debug for full output:
ValueError: "@jupyterlab/vega3-extension" is not a valid npm package
```

**Comment by jakevdp** [comment]
That's very strange... it seems to be looking for the extension on github rather than from the npm servers.

What version of npm do you have?
```
$ npm --version
```

**Comment by ijlyttle** [comment]
Yikes:

```
$ npm --version

module.js:340
    throw err;
          ^
Error: Cannot find module 'child-process-close'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:15:1
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:474:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Let me see what I can do to get npm working. Thanks for starting me on the path, I'll report back soon!

**Comment by ijlyttle** [comment]
Following some wrestling with homebrew, I got node and npm working properly - everything fell into place from there.

Thanks for pointing me in the right direction - really looking forward to exploring now!

**Comment by jakevdp** [comment]
Great, glad it worked!

Fortunately, once the next Jupyterlab release comes out (I've been told in the next couple weeks) the vega3 extension will be built-in, and so this won't be an issue anymore :smile:
