### ISSUE TITLE
"Chart({..." appearing instead of a figure

### ISSUE THREAD

**Issue by eelsirhc** [altair-viz/altair#716]
I'm running Jupyterlab 0.32, Altair 2.0.0dev, but I can't get a rendered figure from the iris dataset. Instead I get the "Chart({ object returned as an *altair.vegalite.v2.api.Chart* object (and the \_\_repr\_\_'d into the notebook/lab).

Any ideas where I failed in the installation? (I installed juptyerlab, the vega notebook extensions, altair 1.x worked fine)

<img width="823" alt="screen shot 2018-04-05 at 10 27 07 pm" src="https://user-images.githubusercontent.com/1069709/38400990-050a0c1e-3921-11e8-991d-120af3b8c500.png">

**Comment by jakevdp** [comment]
It looks like you have not installed the vega3 jupyter extension.

Please follow the installation instructions [here](https://altair-viz.github.io/getting_started/installation.html#installing-altair-with-jupyterlab), make sure to run the ``jupyter labextension install ...`` command, then start JupyterLab within the same environment where you installed the lab extension.

**Comment by eelsirhc** [comment]
The extension reports that it's installed 

    bash-3.2$ jupyter labextension list
    JupyterLab v0.32.0.dev0
    Known labextensions:
       app dir: /Users/lee/anaconda3/share/jupyter/lab
    @jupyterlab/vega3-extension
            @jupyterlab/vega3-extension v0.14.4  enabled  OK

After trying an 'install' again, which fails/passes silently I tried to uninstall

```
bash-3.2$ jupyter labextension uninstall  @jupyterlab/vega3-extension
Uninstalling core extension @jupyterlab/vega3-extension
> node /Users/lee/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency 
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 24.11s.
> node /Users/lee/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
$ webpack --config webpack.prod.config.js
Hash: 8818c30c929f7d889021
Version: webpack 2.7.0
Time: 24468ms
                                 Asset     Size  Chunks                    Chunk Names
        vendor.63914b7e0341387a4a04.js  1.58 MB       2  [emitted]  [big]  vendor
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]         
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]         
             0.ad1eb128b51a8c0b84ab.js   458 kB       0  [emitted]  [big]  
          main.927a7f22614fb8601412.js  1.68 MB       1  [emitted]  [big]  main
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
      manifest.07f14c6116f205e3e5c9.js  1.62 kB       3  [emitted]         manifest
         0.ad1eb128b51a8c0b84ab.js.map  1.34 MB       0  [emitted]         
      main.927a7f22614fb8601412.js.map  5.57 MB       1  [emitted]         main
    vendor.63914b7e0341387a4a04.js.map  5.71 MB       2  [emitted]         vendor
  manifest.07f14c6116f205e3e5c9.js.map  8.24 kB       3  [emitted]         manifest
                            index.html  1.53 kB          [emitted]         
[/sZe] ./~/@phosphor/commands/lib/index.js 33.2 kB {2} [built]
[2Kj9] ./~/@phosphor/widgets/lib/index.js 1.34 kB {2} [built]
[6nap] ./~/ajv/lib/ajv.js 15.2 kB {2} [built]
[l9te] ./~/@phosphor/application/lib/index.js 18.1 kB {2} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {2} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {2} [built]
[o73R] ./~/sanitize-html/index.js 11.2 kB {2} [built]
[q1RZ] ./~/@phosphor/datagrid/lib/index.js 793 bytes {2} [built]
[qzHn] ./~/@phosphor/coreutils/lib/index.js 721 bytes {2} [built]
[rplX] ./~/whatwg-fetch/fetch.js 13 kB {1} [built]
   [6] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/
@phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/
signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json 
path-posix react react-dom sanitize-html url-parse xterm 328 bytes {2} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {2} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {2} [built]
[wuIn] ./~/comment-json/index.js 103 bytes {2} [built]
   [7] multi whatwg-fetch ./build/index.out.js 40 bytes {1} [built]
    + 1257 hidden modules
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.41 kB {0} [built]
✨  Done in 26.28s.
```

But that doesn't work (?)

```
bash-3.2$ jupyter labextension list
JupyterLab v0.32.0.dev0
Known labextensions:
   app dir: /Users/lee/anaconda3/share/jupyter/lab
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.14.4  enabled  OK
```

So I uninstalled jupyter and  jupyterlab, reinstalled from v0.31

```
bash-3.2$ pip install jupyterlab
Collecting jupyterlab
  Using cached jupyterlab-0.31.12-py2.py3-none-any.whl
Requirement already satisfied: ipython-genutils in /Users/lee/anaconda3/lib/python3.6/site-packages (from jupyterlab)
Requirement already satisfied: notebook>=4.3.1 in /Users/lee/anaconda3/lib/python3.6/site-packages (from jupyterlab)
Requirement already satisfied: jupyterlab-launcher<0.11.0,>=0.10.0 in /Users/lee/anaconda3/lib/python3.6/site-packages (from jupyterlab)
Requirement already satisfied: jsonschema>=2.6.0 in /Users/lee/anaconda3/lib/python3.6/site-packages (from jupyterlab-launcher<0.11.0,>=0.10.0->jupyterlab)
Installing collected packages: jupyterlab
Successfully installed jupyterlab-0.31.12
```

Reinstalled the extension

```
bash-3.2$ jupyter labextension list
JupyterLab v0.31.12
No installed extensions
bash-3.2$ jupyter labextension install @jupyterlab/vega3-extension
> /usr/local/bin/npm pack @jupyterlab/vega3-extension
jupyterlab-vega3-extension-0.14.4.tgz
> node /Users/lee/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] 📃  Building fresh packages...
[-/3] ⠠ waiting...
[2/3] ⠠ canvas: using node@9.11.1 | darwin | x64
[3/3] ⠠ fsevents: info it worked if it ends with ok
[-/3] ⠠ waiting...
warning Error running install script for optional dependency: "/Users/lee/anaconda3/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /Users/lee/anaconda3/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@9.11.1 | darwin | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Python executable \"/Users/lee/anaconda3/bin/python\" is v3.6.0, which is not supported by gyp.\ngyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\ngyp ERR! stack     at PythonFinder.failPythonVersion (/Users/lee/.config/yarn/global/node_modules/node-gyp/lib/configure.js:492:19)\ngyp ERR! stack     at PythonFinder.<anonymous> (/Users/lee/.config/yarn/global/node_modules/node-gyp/lib/configure.js:474:14)\ngyp ERR! stack     at ChildProcess.exithandler (child_process.js:265:7)\ngyp ERR! stack     at ChildProcesssuccess Saved lockfile.
✨  Done in 37.20s.
> node /Users/lee/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
Hash: 0dc3a227f53478ae9918
Version: webpack 2.7.0
Time: 33167ms
                                 Asset     Size  Chunks                    Chunk Names
        vendor.3d8ddc2f622a3710dfc1.js  1.58 MB       3  [emitted]  [big]  vendor
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]         
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
             0.69f7a4246d50aa2e9fbc.js   600 kB       0  [emitted]  [big]  vega2
             1.697f116e8467e0f2ccc6.js   458 kB       1  [emitted]  [big]  
          main.55abdebd128310f74d05.js  2.18 MB       2  [emitted]  [big]  main
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]         
      manifest.39105b4016ad3e28576d.js  1.65 kB       4  [emitted]         manifest
         0.69f7a4246d50aa2e9fbc.js.map  2.22 MB       0  [emitted]         vega2
         1.697f116e8467e0f2ccc6.js.map  1.34 MB       1  [emitted]         
      main.55abdebd128310f74d05.js.map  8.74 MB       2  [emitted]         main
    vendor.3d8ddc2f622a3710dfc1.js.map  5.72 MB       3  [emitted]         vendor
  manifest.39105b4016ad3e28576d.js.map  8.29 kB       4  [emitted]         manifest
                            index.html  1.53 kB          [emitted]         
[+HaM] ./~/@phosphor/messaging/lib/index.js 18.5 kB {3} [built]
[/sZe] ./~/@phosphor/commands/lib/index.js 33.2 kB {3} [built]
[8U58] ./~/codemirror/lib/codemirror.js 352 kB {3} [built]
[GiK3] ./~/react/index.js 190 bytes {3} [built]
[O27J] ./~/react-dom/index.js 1.36 kB {3} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {3} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {3} [built]
[l9te] ./~/@phosphor/application/lib/index.js 18.1 kB {3} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {3} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {3} [built]
[q1RZ] ./~/@phosphor/datagrid/lib/index.js 793 bytes {3} [built]
   [9] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {3} [built]
  [10] multi whatwg-fetch ./build/index.out.js 40 bytes {2} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {3} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {3} [built]
    + 2410 hidden modules
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.41 kB {0} [built]
✨  Done in 34.72s.
```

**Note the error in using *gyp* in the node install process. *gyp* requires Python 2.7 I guess. And the unmet dependency or incorrect dependency errors regarding react**

But it claims to install
```
ash-3.2$ jupyter labextension list
JupyterLab v0.31.12
Known labextensions:
   app dir: /Users/lee/anaconda3/share/jupyter/lab
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.14.4  enabled  OK
```

Still no luck
<img width="917" alt="screen shot 2018-04-06 at 9 09 45 am" src="https://user-images.githubusercontent.com/1069709/38423643-78caf89c-397c-11e8-87de-d8987ceacd3a.png">

**Comment by eelsirhc** [comment]
```
node --version
v9.11.1
```

I uninstalled jupyterlab (0.31), updated my anaconda install, which included
```
jupyter_client:                     4.4.0-py36_0                     --> 5.2.3-py36_0                  conda-forge
jupyter_console:                    5.0.0-py36_0                     --> 5.2.0-py36_0                  conda-forge
jupyter_core:                       4.2.1-py36_0                     --> 4.4.0-py_0                    conda-forge
jupyter:                            1.0.0-py36_3                     --> 1.0.0-py_1                    conda-forge
```
and reinstalled jupyterlab. That seems to work, and the altair demos I tried worked. No idea which component needed to be updated.

Thanks for your help.

**Comment by jakevdp** [comment]
I suspect what happened is that you initially installed jupyterlab with conda, and then everything you were doing since then was with pip.

pip and conda are different environment managers, and though they can (sort of) work together in most cases, one can't properly track, uninstall, or update dependencies installed by the other.

If I'd known you were working in a conda environment, I would have recommended you use conda instead of pip to install and update jupyterlab, and I believe that would have worked.
